[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/v2-core/=lib/v2-core/contracts/",
    "@uniswap/v2-periphery/=lib/v2-periphery/contracts/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1000

[rpc_endpoints]
sepolia = "${RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
